export const dealFields = [
    { name: 'username', type: 'text' },
    { name: 'subject', type: 'text' },
    { name: 'phone', type: 'tel' },
    { name: 'email', type: 'email' },
    { name: 'service_id', type: 'int' },
    { name: 'group_id', type: 'int' },
    { name: 'assignee_id', type: 'int' },
    { name: 'pipeline_id', type: 'int' },
    { name: 'pipeline_stage_id', type: 'int' },
    { name: 'estimated_closed_date', type: 'DateTime YYYY-MM-DD HH:mm:ss' },
    { name: 'probability', type: 'int' },
    { name: 'value', type: 'int' },
    { name: 'comment', type: 'text' },
    { name: 'comment.body', type: 'text' },
    { name: 'comment.is_public', type: 'int (1=public, 0=private)' },
    { name: 'comment.author_id', type: 'int' },
    { name: 'order_address_detail', type: 'string' },
    { name: 'order_buyer_note', type: 'string' },
    { name: 'order_city_id', type: 'string' },
    { name: 'order_district_id', type: 'string' },
    { name: 'order_ward_id', type: 'string' },
    { name: 'order_receiver_name', type: 'string' },
    { name: 'order_receiver_phone', type: 'string' },
    { name: 'order_shipping_fee', type: 'float' },
    { name: 'order_status', type: 'string' },
    { name: 'order_tracking_code', type: 'string' },
    { name: 'order_tracking_url', type: 'link' },
    {
        name: 'order_products',
        type: 'array',
        subFields: [
            { name: 'sku', type: 'string' },
            { name: 'is_free', type: 'int (1=true, 0=false)' },
            { name: 'unit_price', type: 'float' },
            { name: 'quantity', type: 'int' },
            { name: 'discount_markup', type: 'float' },
            { name: 'discount_value', type: 'float' },
        ],
    },
];

export const webhookFields = [
    'orderId',
    'shopOrderId',
    'saleChannel',
    'type',
    'typeId',
    'moneyDiscount',
    'moneyDeposit',
    'moneyTransfer',
    'creditAmount',
    'usedPoints',
    'moneyUsedPoints',
    'shipFee',
    'codFee',
    'customerShipFee',
    'calcTotalMoney',
    'description',
    'customerId',
    'customerName',
    'customerEmail',
    'customerMobile',
    'customerAddress',
    'shipToCityLocationId',
    'shipToDistrictLocationId',
    'shipToWardLocationId',
    'customerCity',
    'customerDistrict',
    'customerWard',
    'createdById',
    'couponCode',
    'status',
    'statusDescription',
    'depotId',
    'trackingUrl',
    'createdDateTime',
    {
        name: 'products',
        type: 'array',
        subFields: [
            { name: 'id', type: 'string' },
            { name: 'quantity', type: 'int' },
            { name: 'price', type: 'float' },
            { name: 'discount', type: 'float' },
            { name: 'weight', type: 'float' },
        ],
    },
];