export const webhookFields = [
    { name: 'orderId' },
    { name: 'shopOrderId' },
    { name: 'saleChannel' },
    { name: 'type' },
    { name: 'typeId' },
    { name: 'moneyDiscount' },
    { name: 'moneyDeposit' },
    { name: 'moneyTransfer' },
    { name: 'creditAmount' },
    { name: 'usedPoints' },
    { name: 'moneyUsedPoints' },
    { name: 'shipFee' },
    { name: 'codFee' },
    { name: 'customerShipFee' },
    { name: 'calcTotalMoney' },
    { name: 'description' },
    { name: 'customerId' },
    { name: 'customerName' },
    { name: 'customerEmail' },
    { name: 'customerMobile' },
    { name: 'customerAddress' },
    { name: 'shipToCityLocationId' },
    { name: 'shipToDistrictLocationId' },
    { name: 'shipToWardLocationId' },
    { name: 'customerCity' },
    { name: 'customerDistrict' },
    { name: 'customerWard' },
    { name: 'createdById' },
    { name: 'couponCode' },
    { name: 'status' },
    { name: 'statusDescription' },
    { name: 'depotId' },
    { name: 'trackingUrl' },
    { name: 'createdDateTime' },
    { name: 'reason' },
    { name: 'deliveryDate' },
    {
        name: 'products',
        type: 'array',
        subFields: [
            { name: 'id', type: 'string' },
            { name: 'quantity', type: 'int' },
            { name: 'price', type: 'float' },
            { name: 'discount', type: 'float' },
            { name: 'weight', type: 'float' },
        ],
    },
];
